- name: 1c. Install MariaDB server package
  yum: name=mariadb-server state=present

- name: 2. Start Mysql Service
  service: name=mariadb state=started enabled=true
- name: Install python Mysql package #required for mysql_db tasks
  yum: name=PyMySQL  state=present
- name: 3. Create a new database
  mysql_db: name=demo state=present 

- name: 4. Create a database user
  mysql_user: name=demo password=demo priv=*.*:ALL host=localhost state=present

- name: 5a. Copy sample data
  copy: src=dump.sql dest=/tmp/dump.sql

- name: 5b. Insert sample data
  shell: cat /tmp/dump.sql | mysql -u demo -pdemo demo

